<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DeptDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $data = [
            [
                'cust_name' => 'Philip, Ruth',
                'emp_code' => '00585688',
                'gross_pay' => 5247.49,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Rema, Jorem',
                'emp_code' => '10210703',
                'gross_pay' => 1889.48,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'TSIHAKOU, ABIGAIL',
                'emp_code' => '10689461',
                'gross_pay' => 1507.42,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Wakit, Welmah',
                'emp_code' => '10862201',
                'gross_pay' => 2666.76,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Jimberi, Jacklyn',
                'emp_code' => '12481532',
                'gross_pay' => 1384.48,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Fonn, Tolopato Mary',
                'emp_code' => '00488518',
                'gross_pay' => 1510.62,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Gelo, Gisola',
                'emp_code' => '00548871',
                'gross_pay' => 1613.94,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Sogowa, Lucy',
                'emp_code' => '01575828',
                'gross_pay' => 1584.46,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Edward, Miriam',
                'emp_code' => '10069730',
                'gross_pay' => 1200.78,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Nega, Salagowato',
                'emp_code' => '10321646',
                'gross_pay' => 1507.42,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Auma, Lotter',
                'emp_code' => '10322535',
                'gross_pay' => 1468.83,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Damela, Uwa',
                'emp_code' => '10416678',
                'gross_pay' => 1413.24,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Paine, Wendy',
                'emp_code' => '11142773',
                'gross_pay' => 1413.24,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Ananga, Jerusha',
                'emp_code' => '11250661',
                'gross_pay' => 1413.24,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Salangau, Rollen',
                'emp_code' => '13195508',
                'gross_pay' => 1229.02,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Bibi, Julie',
                'emp_code' => '13275983',
                'gross_pay' => 1229.02,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Thomas, Buka Junior',
                'emp_code' => '13394683',
                'gross_pay' => 1266.52,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'GOGUSO, Gipson',
                'emp_code' => '13477913',
                'gross_pay' => 1266.52,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Dauri, Wendy',
                'emp_code' => '13512563',
                'gross_pay' => 1266.52,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Mewa, Cathy',
                'emp_code' => '13514735',
                'gross_pay' => 1229.02,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Olewale, Tuwe',
                'emp_code' => '10208185',
                'gross_pay' => 1468.83,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Tabua, Hilry',
                'emp_code' => '11274466',
                'gross_pay' => 1413.24,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Tubai, Tupolam',
                'emp_code' => '0060066A',
                'gross_pay' => 1468.83,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Gorgom, Pamela',
                'emp_code' => '12717681',
                'gross_pay' => 1413.24,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Maim, Molly',
                'emp_code' => '12961454',
                'gross_pay' => 1266.52,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Lalamo, Michael Gim',
                'emp_code' => '13005455',
                'gross_pay' => 1302.94,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'cust_name' => 'Lowa, Karam Willie',
                'emp_code' => '13829950',
                'gross_pay' => 1192.64,
                'company_id' => 1,
                'organization_id' => 0,
                'net_pay' => 0,
                'phone' => null,
                'email' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('all_cust_master')->insert($data);
    }
}
