<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Log;

class FrontEndController extends Controller
{
    public function sendLoanMail (Request $request)
    {
        dd($request);
        $validated = $request->validate([
            'amount' => 'required|numeric|min:0',
            'tenure' => 'required|integer|min:1',
            'repaymentPlan' => 'nullable|string|max:255',
            'name' => 'required|string|max:255',
            'phone' => 'required|string|max:50',
            'email' => 'required|email|max:255',
            'service' => 'nullable|string|max:255',
        ]);

        try {
            // Destination for inquiries: use MAIL_FROM_ADDRESS or fallback env value
            $adminEmail = config('mail.from.address') ?? env('MAIL_ADMIN_ADDRESS', 'admin@example.com');

            // Build plain-text body
            $bodyLines = [
                "New loan inquiry received from website",
                "-------------------------------------",
                "Name: " . ($validated['name'] ?? '-'),
                "Email: " . ($validated['email'] ?? '-'),
                "Phone: " . ($validated['phone'] ?? '-'),
                "Service: " . ($validated['service'] ?? '-'),
                "Amount: " . ($validated['amount'] ?? '-'),
                "Tenure (days): " . ($validated['tenure'] ?? '-'),
                "Estimated Repayment: " . ($validated['repaymentPlan'] ?? '-'),
                "",
                "This message was generated by the frontend loan enquiry form."
            ];
            $body = implode("\n", $bodyLines);

            Mail::raw($body, function ($message) use ($validated, $adminEmail) {
                $message->to($adminEmail)
                        ->subject('Website Loan Inquiry — ' . ($validated['name'] ?? 'Unknown'));
                if (!empty($validated['email'])) {
                    $message->replyTo($validated['email'], $validated['name'] ?? null);
                }
            });

            return response()->json([
                'message' => '✅ Your inquiry was sent successfully. We will contact you shortly.'
            ], 200);
        } catch (\Exception $e) {
            Log::error('send_loan_calc_mail error: ' . $e->getMessage());

            return response()->json([
                'message' => '❌ Failed to send inquiry. Please try again later.',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
